# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ehci_pci" "ahci" "ums_realtek" "usbhid" "usb_storage" "sd_mod" "sr_mod"];
  #boot.initrd.availableKernelModules = ["xhci_pci" "ehci_pci" "ahci" "ums_realtek" "usbhid" "usb_storage" "sd_mod" "sr_mod" "virtio_blk" "virtio_pci"];
  boot.initrd.kernelModules = [];
  boot.kernelParams = ["intel_iommu=on" "iommu=pt"];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];
  networking.hostId = "d7630388";
  boot.zfs.devNodes = "/dev/disk/by-partlabel";

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
